export type PrivacyPolicyBlock = {
  type: "meta" | "divider" | "heading" | "paragraph" | "listItem";
  text: string;
};

export const privacyPolicyBlocks: PrivacyPolicyBlock[] = [
  {
    type: "meta",
    text: "Version: 1.1 (GDPR, CCPA and COPPA Compliant Standard)\nEffective Date: May 17, 2026\nLanguage: English",
  },
  {
    type: "divider",
    text: "",
  },
  {
    type: "paragraph",
    text: "Welcome to Everyday!",
  },
  {
    type: "paragraph",
    text: "Your privacy is our highest priority. Everyday is committed to establishing a safe, transparent, and secure digital environment that respects your control over your personal data.",
  },
  {
    type: "paragraph",
    text: "This Privacy Policy describes how Everyday collects, uses, stores, processes, and protects your personal information when you install and use the Everyday mobile application, including our lock screen widgets and live activities.",
  },
  {
    type: "paragraph",
    text: "By registering an account, logging in via Google authentication, or granting Everyday permission to access your location services, you acknowledge that you agree to the terms of this Privacy Policy. We are strictly committed to never selling your personal data to any third parties.",
  },
  {
    type: "heading",
    text: "SECTION 1: DATA COLLECTION AND METHODS",
  },
  {
    type: "paragraph",
    text: "We collect only the information necessary to provide you with a high-fidelity fitness logging and social networking experience.",
  },
  {
    type: "paragraph",
    text: "1.1 Authentication and Account Information\nMethod: Everyday utilizes secure authentication services provided by trusted third-party authentication providers.\nCollected Data:\na. The email address associated with your registered account.\nb. A unique User ID (UUID format) generated to identify your account across our system database.\nc. Basic profile information associated with your authentication provider account (such as your default name) as permitted by your third-party sharing settings.",
  },
  {
    type: "paragraph",
    text: "1.2 Profile Information\nDuring the initial onboarding flow, Everyday collects parameters to customize your user experience:\na. Your chosen display name or nickname.\nb. A profile picture or avatar uploaded from your device photo library.\nc. Your declared age.\nd. A list of your favorite sports or physical activities.",
  },
  {
    type: "paragraph",
    text: "1.3 GPS Location and Physical Activity Data\nGPS Coordinates:\na. Explicit Consent: Everyday collects location coordinates only with your explicit permission. When you initiate a workout recording, the application will prompt you for location access permissions.\nb. Background Location Tracking: To draw an accurate route map and update metrics on your lock screen Live Activity widget while your screen is off, Everyday collects your GPS location in the background during active workout sessions.\nc. Termination of Collection: Location tracking terminates immediately when you tap to save or end your active session.\nActivity Metrics: Workout duration, distance covered, average speed, and activity type (such as running or cycling).",
  },
  {
    type: "paragraph",
    text: "1.4 Social and Friendship Data\nYour list of established friendships and pending friend requests, which are processed to generate your social activity feed where friends can interact with each other's workout records.",
  },
  {
    type: "paragraph",
    text: "1.5 Feedback and Support Submissions\nWhen you submit feedback via the application settings, we collect your account email address and your written feedback content. This data is transmitted directly to a secure feedback management system maintained by our administration team and is not stored on our primary application database.",
  },
  {
    type: "paragraph",
    text: "1.6 Push Notification Data\nEveryday collects device push notification tokens generated by Apple Push Notification service (APNs). These tokens are used only to deliver app notifications, such as friend requests, friend request acceptance updates, and other activity-related notifications.",
  },
  {
    type: "heading",
    text: "SECTION 2: HOW WE USE YOUR INFORMATION",
  },
  {
    type: "paragraph",
    text: "Everyday processes your personal information strictly for the following lawful purposes:",
  },
  {
    type: "listItem",
    text: "Core Service Operations: To authenticate your account, maintain your user profile, and synchronize your physical activity history across devices using our secure application database.",
  },
  {
    type: "listItem",
    text: "Route and Mapping Features: To utilize GPS coordinates to render your routes and pathways on your interactive workout map.",
  },
  {
    type: "listItem",
    text: "Live Activity Updates: To transmit real-time fitness metrics (such as speed and distance) to your lock screen Live Activity widget.",
  },
  {
    type: "listItem",
    text: "Social Networking Features: To display your workouts, route maps, and speed metrics on the Feed of users with whom you have established a friendship.",
  },
  {
    type: "listItem",
    text: "Technical Improvements and Debugging: To evaluate user submissions sent via our feedback channel to resolve software bugs and enhance system features.",
  },
  {
    type: "heading",
    text: "SECTION 3: DATA STORAGE AND SECURITY",
  },
  {
    type: "paragraph",
    text: "We have designed our backend architecture to comply with modern security standards:",
  },
  {
    type: "listItem",
    text: "Structured Data: All user profiles, friendships, friend requests, and workout records are securely hosted in our application database.",
  },
  {
    type: "listItem",
    text: "Profile Avatars and Activity Images: Images are uploaded and served via secure cloud storage.",
  },
  {
    type: "listItem",
    text: "Feedback Storage: User feedback is routed securely to our feedback management system via secure API endpoints.",
  },
  {
    type: "listItem",
    text: "Data Transmission Security: All data exchanged between your mobile device and our cloud services is fully encrypted using HTTPS/TLS 1.3 protocol.",
  },
  {
    type: "listItem",
    text: "Data Isolation (Row Level Security): We enforce Row Level Security (RLS) policies on our database tables. Every client request must be validated with a verified JSON Web Token (JWT). This architecture ensures that a user can never access or modify the private data of another user, ensuring total data isolation.",
  },
  {
    type: "heading",
    text: "SECTION 4: DATA SHARING AND THIRD-PARTY PROCESSORS",
  },
  {
    type: "paragraph",
    text: "Everyday does not sell, trade, or rent your personal information or GPS location data to any advertising agencies, commercial marketing platforms, or third parties.",
  },
  {
    type: "paragraph",
    text: "We share data only under the following limited circumstances:",
  },
  {
    type: "listItem",
    text: "With Your Friends: Your route maps, workouts, avatars, and nicknames are visible to users whom you have accepted as friends. You can unfriend or block any user at any time to immediately revoke their access to your data.",
  },
  {
    type: "listItem",
    text: "Infrastructure Sub-processors:\na. Authentication providers: Support secure account sign-in and session management.\nb. Database providers: Store user profiles, workout records, friendships, and related application data.\nc. Cloud storage providers: Manage and distribute profile pictures and activity images.\nd. Mapping providers: Provide map rendering services for displaying workout routes.\ne. Platform service providers: Provide system services such as push notifications, Live Activities, and app distribution.",
  },
  {
    type: "listItem",
    text: "Legal Compliance: We may disclose your personal information if required to do so by law or in response to valid requests by public authorities.",
  },
  {
    type: "heading",
    text: "SECTION 5: CHILD PRIVACY (COPPA COMPLIANCE)",
  },
  {
    type: "listItem",
    text: "We do not knowingly collect or request personal data from anyone under the age of 13.",
  },
  {
    type: "listItem",
    text: "In the event that we discover we have inadvertently collected personal data from a child under 13 without verifiable parental consent, we will take immediate steps to permanently delete that information from our application database and secure cloud storage.",
  },
  {
    type: "heading",
    text: "SECTION 6: YOUR RIGHTS (GDPR AND CCPA COMPLIANCE)",
  },
  {
    type: "paragraph",
    text: "Everyday provides you with full control over your personal data directly from the Settings panel:",
  },
  {
    type: "listItem",
    text: "Right to Access: You have the right to request a copy of your personal data, including your workout history and location records.",
  },
  {
    type: "listItem",
    text: "Right to Rectification: You can update your display name, age, and profile avatar at any time via the Settings menu.",
  },
  {
    type: "listItem",
    text: "Right to Terminate Tracking: You can revoke Everyday's access to location services at any time within your iOS system settings. The application remains functional for indoor activities that do not require maps.",
  },
  {
    type: "listItem",
    text: "Right to Erasure (Delete Account): You have the right to request the permanent deletion of your account. When you trigger the account deletion action in the Settings panel:\na. Your user record on the application database will be permanently deleted.\nb. All of your friendships and pending friend requests will be revoked.\nc. All of your physical activity records and historical GPS routes will be permanently wiped from our databases.",
  },
  {
    type: "heading",
    text: "SECTION 7: CONTACT AND SUPPORT",
  },
  {
    type: "paragraph",
    text: "If you have any questions, requests to access your data, or support inquiries regarding this Privacy Policy, please contact us using the \"Feedback for us\" channel integrated directly within the Settings menu of the Everyday application.",
  },
  {
    type: "paragraph",
    text: "For additional support, please contact:\nEmail: meetwaaron@gmail.com",
  },
];
